name: 'eu_flights_project'
version: '1.0.0'
config-version: 2

profile: 'eu_flights_project'

models:
  eu_flights_project:
    staging:
      +materialized: view
    marts:
      +materialized: view
